baseURL = 'https://frreinert.github.io/resume/'
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true
theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

[author]
name = 'Fabricio Roberto Reinert'

[languages]
  [languages.en]
    url = 'en/'
    title = 'Resume - Fabricio Roberto Reinert'
    languageName = 'English'
    weight = 3
  [languages.pt]
    url = 'pt/'
    languageName = 'Português'
    title = 'CV - Fabricio Roberto Reinert'
    weight = 2

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#e3bfb8"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#e3bfb8"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#e3bfb8"
pages = 3
swapColumns = false # Set this param to 'true' to swap the bar positions
